name: Build MPC-BE

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup MSYS/MinGW toolchain
        run: |
          .\toolchains\setup-msys.ps1
        shell: pwsh

      - name: Copy GCC runtime libs
        run: |
          .\update_gcc.bat
        shell: cmd

      - name: Clean
        run: .\build.bat Clean All NoWait
        shell: cmd

      - name: Build MPC-BE
        run: .\build.bat Build Packages NoWait
        shell: cmd

      - name: Upload Installer x64
        uses: actions/upload-artifact@v4
        with:
          name: Installer-x64
          path: _bin/Packages/**/MPC-BE*.x64-installer.zip
          compression-level: 0

      - name: Upload 7z x64
        uses: actions/upload-artifact@v4
        with:
          name: Package-x64
          path: _bin/Packages/**/MPC-BE*.x64.7z
          compression-level: 0

      - name: Upload Installer x86
        uses: actions/upload-artifact@v4
        with:
          name: Installer-x86
          path: _bin/Packages/**/MPC-BE*.x86-installer.zip
          compression-level: 0

      - name: Upload 7z x86
        uses: actions/upload-artifact@v4
        with:
          name: Package-x86
          path: _bin/Packages/**/MPC-BE*.x86.7z
          compression-level: 0
